
imagePullSecrets: []

yurtControllerManager:
  replicaCount: 1
  tolerations: []
  image:
    registry: docker.io
    repository: openyurt/yurt-controller-manager
    pullPolicy: IfNotPresent
    tag: v1.1.0
  service:
    type: ClusterIP
    port: 80

admissionWebhooks:
  enabled: true
  service:
    type: ClusterIP
    port: 9443
  failurePolicy: Fail
  certificate:
    mountPath: /tmp/k8s-webhook-server/serving-certs
  patch:
    enabled: true
    image:
      repository: docker.io/oamdev/kube-webhook-certgen
      tag: v2.4.1
      pullPolicy: IfNotPresent
    affinity: {}
    tolerations: [{"key": "node-role.kubernetes.io/master", "operator": "Exists", "effect": "NoSchedule"}]
  certManager:
    enabled: false
    revisionHistoryLimit: 3

yurtTunnelAgent:
  replicaCount: 1
  tolerations: []
  parameters:
    tunnelserverAddr: ""
  image:
    registry: docker.io
    repository: openyurt/yurt-tunnel-agent
    pullPolicy: IfNotPresent
    tag: v1.1.0

yurtTunnelServer:
  replicaCount: 1
  tolerations: []
  parameters:
    certDnsNames: ""
    certIps: ""
  image:
    registry: docker.io
    repository: openyurt/yurt-tunnel-server
    pullPolicy: IfNotPresent
    tag: v1.1.0

yurtHub:
  cacheAgents: ""
